title:             Clean Blog
email:             eddy83y@gmail.com
description:       A Blog Theme by Start Bootstrap
author:            Eddy Park
baseurl:           ""
url:               "http://eddy83y.github.io"

# Social Profiles
twitter_username:  
github_username:   eddy83y
facebook_username: 

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
